{% set version = "2.10.0" %}

package:
  name: tvb-library
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/t/tvb-library/tvb_library-{{ version }}.tar.gz
  sha256: cd4ad32dcf4c58a8b926bd30baed269272d217d92605e308d7d3f22d900b8641

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python
    - hatchling
  run:
    - python
    - autopep8
    - networkx
    - numpy <2
    - numba
    - numexpr
    - mako
    - matplotlib-base
    - scipy
    - six
    - deprecated
    - ipywidgets
    - docutils

test:
  imports:
    - tvb.simulator.lab

about:
  home: http://www.thevirtualbrain.com/
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: A package for performing whole brain simulations
  description: |
    The Virtual Brain Project (TVB Project) has the purpose of offering some |
    modern tools to the Neurosciences community, for computing, simulating |
    and analyzing functional and structural data of human brains. |
    "TVB Scientific Library" is the most important scientific contribution |
    of TVB Project, but only a part of our code.
  doc_url: http://docs.thevirtualbrain.org/
  dev_url: https://github.com/the-virtual-brain/tvb-library

extra:
  recipe-maintainers:
    - liadomide
    - popaula937
