{% set name = 'tvb-library' %}
{% set version = "1.5.8" %}
{% set sha256 = "022400ddeda857b09704892114e7812f202d91fe4547d887b527098295127888" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/t/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python -m pip install . --no-deps -vv
  skip: True  # [py>27]

requirements:
  build:
    - python
  host:
    - pip
  run:
    - python
    - tvb-gdist
    - networkx
    - nibabel
    - numpy
    - numba
    - numexpr
    - matplotlib
    - scikit-learn
    - scipy

test:
  imports:
    - tvb.simulator.lab

about:
  home: http://www.thevirtualbrain.com/
  license: GPL-3.0
  license_family: GPL
  license_file: LICENSE
  summary: 'A package for performing whole brain simulations'
  description: |
    The Virtual Brain Project (TVB Project) has the purpose of offering some |
    modern tools to the Neurosciences community, for computing, simulating |
    and analyzing functional and structural data of human brains. |
    "TVB Scientific Library" is the most important scientific contribution |
    of TVB Project, but only a part of our code.
  doc_url: http://docs.thevirtualbrain.org/
  dev_url: https://github.com/the-virtual-brain/tvb-library

extra:
  recipe-maintainers:
    - liadomide
