appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
travis:
  secure: {BINSTAR_TOKEN: WlDpYkI7dnkVXgijQuDNevZTOUXJGIJd56aO2pjYX7wH2TbB2kfX+QbXktt2gzDzwLZwvhFXEfM0RK69QTY+nBokXg9Kn9TS2JZTrETwcdoasnQEEp8c31laTsdzX93jRHzt9TYaPDEh9VWLdPTZOUFIOZGzlenndVqQf1oiFI/+wMVh+K0zM1vNDfwmLHR5sceIpqBG/qbEtZ/hJabRZe23pWu2EBWkRjhBXw06A7ufM5emTWmDBaLptWLTtDVkGrMrD0ZB03fnj7CWFc6rAi2FZMueJUSJtjQpBvQLJyMD8hIJV4cbKugdQLHjaIetxf0NjftqkPsYkeh0/swEjSXOkvlkfpc4FWV53rvNP3ErkuUUkd7XRzXidW8el/W+PmWXo9oC+WcrPfMTQs5g/fDt0so6Jy8azdg+b1vHN/2kBTdC/2gcDhv1vBUf6z/NN47yMmOQPn2ijUulWsNpX4OIrOXTlLo7M/3OPbZe4ov7isXZtixlW91vrv3CqadItQ61eZbL1ZLQgAKZR+/2hgTB6nAVpiWTwfAh3+W/OHO5yrl1ZKr6AgL7I1OJge4s301dux5aKyMVukah/kNL7K/BavzqQb61raU596vEicRuVzFTZRF155bqFxQxXHWWyoyT+gPDOcu5i1VGJvG9QfrfV9f0glj5+5/UHMAQ748=}
provider:
  win: azure
conda_forge_output_validation: false
